FORMAT: 1A
HOST: https://panel-id.pdk.io/api

# PDK Panel API

The PDK Panel API provides for programmatic access to CRUD operations on entities and a realtime event stream from the PDK Access Control system.

The API conforms to many of the tenets of the REST style architecture and fully embraces the HTTP standard to fulfill many of these.

* Stateless
* Cacheable
* A URL identifies a Resource
* Operations conveyed implicitly through HTTP verbs

This drives certain uniform architectural attributes of the API.

# Authentication

Authenticating to this stateless API is handled by including an HTTP Authentication header in each request.
Before making any requests to the panel's API andpoint you will need a Bearer token.
This token represents your application's permission to access the API as delegated by the user.

For instructions on retrieving a token for communicating with a panel's API, see the [Auth Server API documentation](http://docs.pdkauthapi.apiary.io/).

Because the API is stateless, this Bearer token must be included in every request to the API.
The Authorization header MUST be of the following format:

`Authorization: Bearer {token-value}` 


# Resource Operations

Standard CRUD operations on resources are performed using HTTP verbs.

* GET - Retrieve a resource, never modifies data
* POST - Create a resource or perform other non-data operations (e.g. trigger a system event)
* PUT - Update a resource
* DELETE - Delete a resource

# Cache Headers

The current state of a resource is identified by standard HTTP caching mechanisms in the response to a requested resource (e.g. ETag, Last-Modified, cache-control).
These headers can be used for change detection and intermediate caching. Standard HTTP caching rules are adhered to by the API server, for example .

# URI Format

Resource URIs will generally follow a format similar to those shown below.

* Resource Collection - `https://panel-id.pdk.io/api/{resource-name}`
* Specific Resource - `https://panel-id.pdk.io/api/{resource-name}/{id}`
* Related Resource Collection - `https://panel-id.pdk.io/api/{resource-name}/{id}/{related-resource}`
* Specific Related Resource - `https://panel-id.pdk.io/api/{resource-name}/{id}/{related-resource}/{id}`

# Content type

Content type is set to `application/json` for all API calls

# Response Codes

## HTTP Codes
* 200 - OK status with json body
* 204 - OK status without body
* 400 - Bad Request
* 401 - Unauthorized
* 403 - Forbidden
* 404 - Not Found
* 422 - Unprocessible Entity
* 500 - Internal Server Error

## Error message format

    {
        "code" : "106",
        "message" : "Person already exists"    
    }

## Error Codes
* 100 - Unprocessible request
* 101 - Unauthorized
* 102 - Access denied
* 103 - Resourse not found
* 104 - Unexpected Server error
* 106 - Entity already exists

# Roles

Roles that system users can have:
* `Reporter` has read only access for Persons, Groups System Events, Auto Open entities.
* `Manager` in addition to `Reporter` permissions has write access for Persons and Groups entities.
* `Admin` in addition to `Manager` permissions has write access for Partitions entities.
* `Integrator` in addition to `Admin` permissions can change hardware configuration.
* `Sysop` in addition to `Admin` permissions can change hardware configuration.

# Group Persons
A person entity represents the attributes of a person that will be interacting with the access control system.
These attributes include the person's name, a list of their credentials, rules that apply to them, and a list of group memberships, among others. 

## Persons Collection [/persons?page={page}&per-page={per_page}&sort={sort_order}]

The functionality is available for [Admin, Manager, Reporter] roles.

### Retrieve all Persons [GET /persons?page={page}&per-page={per_page}&sort={sort_order}]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).

+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    + `id` (required, number) ... Person's id.
    + `name` (required, string) ...  Person's name.
    + `enabled` (optional, string) ... Person's account mode. True by default.
    + `activeDate` (optional, string) ...  Person's account active date. Null by default. 
    + `expDate` (optional, string) ... Person's account expiration date. Null by default.
    
    + Body
    
            {
                "totalCount": "1",
                "items": [
                    {
                        "id": "10",
                        "name": "Ted Froëdington",
                        "enabled": "true",
                        "activeDate": "2016-03-23T18:25:43.511Z",
                        "expDate": "2016-04-23T18:25:43.511Z"
                    }
                ]
            }
            
+ Response 500 (application/json)
        
## Person [/persons/{id}]

##### Performes operations with a single person.
The functionality is available for [Admin, Manager] roles. Retrieving a Person is also available for the [Reporter] role.
### Retrieve a Person [GET]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
    
+ Response 200 (application/json)

    + `id` (required, number) ... Person's id.
    + `name` (required, string) ...  Person's name.
    + `enabled` (optional, string) ... Person's account mode. True by default.
    + `activeDate` (optional, string) ...  Person's account active date. Null by default. 
    + `expDate` (optional, string) ... Person's account expiration date. Null by default.
    
    + Body
    
            {
                "id": "1",
                "name": "Ted Froëdington",
                "enabled": "true",
                "activeDate": "2016-03-23T18:25:43.511Z",
                "expDate": "2016-04-23T18:25:43.511Z"
            }

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Create a Person [POST /persons]

+ Request

    + `name` (required, string) ...  Person's name.
    + `enabled` (optional, string) ... Person's account mode. True by default.
    + `activeDate` (optional, string) ...  Person's account active date. Null by default. 
    + `expDate` (optional, string) ... Person's account expiration date. Null by default.
    
    + Body
            
            {
                "name": "Ted Froëdington",
                "enabled": "true",
                "activeDate": "2016-03-23T18:25:43.511Z",
                "expDate": "2016-04-23T18:25:43.511Z"
            }
            
+ Response 200 (application/json)

    + `id` (required, number) ... Id of created entity.
    
    + Body
    
            {
                "id": "1"
            }

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 422 (application/json)

    + Body
    
            {
                "code": 106,
                "message": "Person already exists."
            }
            
+ Response 500 (application/json)

### Update a Person [PUT]

+ Request

    + `name` (required, string) ...  Person's name.
    + `enabled` (optional, string) ... Person's account mode. True by default.
    + `activeDate` (optional, string) ...  Person's account active date. Null by default. 
    + `expDate` (optional, string) ... Person's account expiration date. Null by default.
    
    + Body
    
            {
                "name": "Ted Froëdington",
                "enabled": "true",
                "activeDate": "2016-03-23T18:25:43.511Z",
                "expDate": "2016-04-23T18:25:43.511Z"
            }
            
+ Response 204

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 422 (application/json)

    + Body
    
            {
                "code": 106,
                "message": "Person already exists."
            }

+ Response 500 (application/json)

### Delete a Person [DELETE]
+ Response 204

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

## Person Photo [/persons/{id}/photo]
The functionality is available for [Admin, Manager] roles.  Retrieving a Photo is also available for the [Reporter] role.
### Retrieve a Photo [GET]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
        
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

    + photoURL (required, string) ... URL of Person's photo.
    
    + Body
    
            {
                "photoUrl": "www.example.com/photo.png"
            }
            
+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Create a Photo [POST]

+ Request

    + Parameters
    
        + `id` (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
        + `photoBase64` (required, string) ... Person's photo in Base64 format
        
    + Headers
    
            Authorization: Bearer {token}
    
    + Body
    
            {
                "photoBase64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA..."
            }

+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Delete a Photo [DELETE]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
            
+ Request
    
    + Headers
    
            Authorization: Bearer {token}
    
+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

## Person Card [/persons/{id}/cards]

The functionality is available for [Admin, Manager] roles.  Retrieving Cards is also available for the [Reporter] role.

### Retrieve all Cards [GET /persons/{id}/cards?page={page}&per-page={per_page}&sort={sort_order}]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).]

+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

    + `id` (required, number, `1`) ... Alphanumeric `id` of the Card.
    + `description` (optional, string) ... Card description (max length 255).
    + `cardNumber` (required, number) ... Card number. 
    
    + Body
    
            {
                "items": [
                    {
                        "id": "1",
                        "description": "myCard",
                        "cardNumber":"12321"
                    }
                ]
            }

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Retrieve a Card [GET /persons/{person_id}/cards/{card_id}]

+ Request

    + Parameters
    
        + `person_id` (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
    
    + Headers
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

    + `id` (required, number, `1`) ... Alphanumeric `id` of the Card.
    + `description` (optional, string) ... Card description (max length 255).
    + `cardNumber` (required, number) ... Card number. 
    
    + Body
    
            {
                "id": "1",
                "description": "Card description",
                "cardNumber": "123"
            }

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Create a Card [POST]
+ Request

    + Parameters
        + `id` (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
        + `description` (optional, string) ... Card description (max length 255).
        + `cardNumber` (required, number) ... Card number. 
    
    + Headers
    
            Authorization: Bearer {token}
            
    + Body
        
            {
                "description": "Card description",
                "cardNumber": "123"
            }
        

+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

### Delete a Card [DELETE /persons/{person_id}/card/{card_id}]
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 404 (application/json)

+ Response 500 (application/json)

## Person Rules Collection [/persons/{id}/rules?page={page}&per-page={per_page}&sort={sort_order}]
#### Managing rules for a person.
The functionality is available for [Admin, Manager, Reporter] roles.
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.

### Retrieve Rules Collection for a Person [GET]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).

+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door
    
    + Body
    
            {
                "totalCount": "1",
                "items": [
                    {
                        "id": "1",
                        "name": "John Smith",
                        "rules": [
                            {
                                "type": "door",
                                "label": "Door21",
                                "id": "1",
                                "allow": "true",
                                "startTime": "12:00",
                                "stopTime": "23:00",
                                "recurring": [
                                    "Monday",
                                    "Tuesday"
                                ],
                                "singleDate": "2016-02-23",
                                "label": "Door21",
                                "doors": [
                                    {
                                        "id": "1"
                                    }
                                ]
                            },
                            {
                                "type": "elevator",
                                "label":"Group3: Door132",
                                "id": "2",
                                "startTime": "12:00",
                                "stopTime": "23:00",
                                "recurring": [
                                    "Monday",
                                    "Tuesday"
                                ],
                                "singleDate": "2016-02-23",
                                "floorGroups": [
                                    {
                                        "id": "1",
                                        "name": "Group3",
                                        "floors": [
                                            {
                                                "id": "12"
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                "type": "event",
                                "sourceLabel": "Door1",
                                "targetLabel": "Door2",
                                "id": "3",
                                "name": "MyEventRule",
                                "triggerType": "When allowed",
                                "action": "Delay Open",
                                "delay": "0:25:43",
                                "startTime": "12:00",
                                "stopTime": "23:00",
                                "recurring": [
                                    "Monday",
                                    "Tuesday"
                                ],
                                "singleDate": "2016-02-23",
                                "sourceDoors": [
                                    {
                                        "id": "1"
                                    }
                                ],
                                "targetDoors": [
                                    {
                                        "id": "2"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

## Person Rules  [/persons/{id}/rules]
The functionality is available for [Admin, Manager] roles. Retrieving a Rule is also available for the [Reporter] role.

### Retrieve a Rule for a Person  [GET /persons/{person_id}/rules/{rule_id}]
+ Parameters

    + person_id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
    + rule_id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.
    
+ Request (application/json)

+ Response 200 (application/json)

    + `id` (required, number) ... Id of created rule.
    
    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed

    + Body
    
            {
                "id": "1",
                "label": "Door121",
                "type": "door",
                "allow": "true",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "doors": [
                    {
                        "id": "132"
                    }
                ]
            }
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Add a Rule for a Person  [POST /persons/{id}/rules]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
    
+ Request (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    + Body
    
            {
                "name": "MyEventRule",
                "triggerType": "When allowed",
                "action": "Delay Open",
                "delay": "0:25:43",
                "type": "event",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "sourceDoors": [
                    {
                        "id": "1"
                    }
                ],
                "targetDoors": [
                    {
                        "id": "2"
                    }
                ]
            }

+ Response 200 (application/json)

    + `id` (required, number) ... Id of created rule.

    + Body
    
            {
                "id":"1"
            }
            
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Update a Rule for a Person [PUT /persons/{person_id}/rules/{rule_id}]

+ Parameters

    + person_id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
    + rule_id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.

+ Request

    + Headers
    
            Authorization: Bearer {token}
            
    + Body
    
            {
                "allow": "true",
                "type": "elevator",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "floorGroups": [
                    {
                        "id": "1"
                    }
                ]
            }

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Delete a Rule for a Person [DELETE /persons/{person_id}/rules/{rule_id}]
+ Parameters

    + person_id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
    + rule_id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.
    
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

## Person Groups [/persons/{id}/groups]
The functionality is available for [Admin, Manager] roles. [Reporter] role has access for retrieving operations only.
### Retrieve all Groups for a Person [GET /persons/{id}/groups?page={page}&per-page={per_page}&sort={sort_order}]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).

+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

    + Body
    
            {
                "totalCount": "1",
                "items": [
                    {
                        "id": "1",
                        "name": "Floor 1"
                    }
                ]
            }

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 500 (application/json)

### Retrieve a Group for a Person  [GET /persons/{person_id}/groups/{group_id}]
+ Parameters
    + person_id (required, string, `1`) ... Alphanumeric `id` of the Person to perform the action on.
    + group_id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.
+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "id": "1",
                "name": "group1"
            }
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Add a Group for a Person [POST /persons/{id}/groups]
+ Request

    + Headers
    
            Authorization: Bearer {token}
    
    + Body
        
            {
                "id": "1"
            }
            
+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 500 (application/json)

### Remove a Person from a Group [DELETE /persons/{person_id}/groups/{group_id}]
+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 204 (application/json)

+ Response 400 (application/json)

+ Response 401 (application/json)

+ Response 403 (application/json)

+ Response 500 (application/json)    

# Group Groups
A group entity represents a set of shared rules that apply to people that are members of the group.

## Groups Collection [/groups?page={page}&per-page={per_page}&sort={sort_order}]
The functionality is available for [Admin, Manager, Reporter] roles.
### Retrieve All Groups [GET]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).
    
+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    + Body
    
            {
                "totalCount" : "1",
                "items": [
                    {
                        "id": "1",
                        "name": "group1"
                    }
                ]
            }
            
+ Response 401 (application/json)
+ Response 500 (application/json)

## Group [/groups/{id}]
#### A distinct group entity.
The functionality is available for [Admin, Manager] roles. Retrieving a Group is also available for the [Reporter] role.
+ Parameters
    + id (required, string, `1`) ... Alphanumeric `id` of the Group to perform the action on.

### Retrieve a Group [GET]
    
+ Response 200 (application/json)

    + `id` (required, number) ... Group id.
    + `name` (required, string) ...  Group name.

    + Body
    
            {
                "id": "1",
                "name": "group1"
            }

+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Create a Group [POST /groups]

+ Request

    +`name` (required, string) Group name
    + Headers
    
            Authorization: Bearer {token}
    + Body
    
            {
                "name": "group1"
            }

+ Response 200 (application/json)

    + `id` (required, number) ... Id of created group.
    + Body
    
            {
                "id": "1"
            }
            
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 422 (application/json)

    + Body
    
            {
                "code": 106,
                "message": "Group already exists"
            }
            
+ Response 500 (application/json)

### Update a Group [PUT]

+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Group to perform the action on.

+ Request

    +`name` (required, string) Group name
    + Headers
    
            Authorization: Bearer {token}
    + Body
    
            {
                "name": "group1"
            }

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 422 (application/json)

    + Body
    
            {
                "code": 106,
                "message": "Group already exists"
            }
            
+ Response 500 (application/json)


### Delete a Group [DELETE]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Group to perform the action on.
    
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

## Group Rules Collection [/groups/{id}/rules?page={page}&per-page={per_page}&sort={sort_order}]

#### Managing rules for a group.

The functionality is available for [Admin, Manager, Reporter] roles.

### Retrieve Rules Collection for a Group [GET]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).
    
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 200 (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door
    
    + Body
            
            {
                "totalCount" : "1",
                "items": [
                    {
                        "id": "1",
                        "name": "Group1",
                        "rules": [
                            {
                                "id": "1",
                                "type":"door",
                                "label":""
                            }
                        ]
                    }
                ]
            }
+ Response 401 (application/json)
+ Response 500 (application/json)

## Group Rules [/groups/{id}/rules]

The functionality is available for [Admin, Manager] roles.

### Add Rule for a Group  [POST /groups/{id}/rules]

+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Group to perform the action on.
    
+ Request (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    + Body
    
            {
                "type": "door",
                "allow": "true",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "doors": [
                    {
                        "id": "1"
                    }
                ]
            }

+ Response 200 (application/json)

    + `id` (required, number) ... Id of created rule.

    + Body
    
            {
                "id": "1"
            }
            
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Update a Rule for a Group [PUT /groups/{group_id}/rules/{rule_id}]

+ Parameters

    + group_id (required, string, `1`) ... Alphanumeric `id` of the Group to perform the action on.
    + rule_id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.

+ Request

    + Headers
    
            Authorization: Bearer {token}
    + Body
    
            {
                "type": "elevator",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "floorGroups": [
                    {
                        "id": "1"
                    }
                ]
            }

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Delete a Rule for a Group [DELETE /groups/{group_id}/rules/{rule_id}]
+ Parameters

    + group_id (required, string, `1`) ... Alphanumeric `id` of the Group to perform the action on.
    + rule_id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.
    
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

# Group System Events

#### List of event rules that apply to system-wide events, which are events not generated by a known person.

## System Events Collection [/system-events?page={page}&per-page={per_page}&sort={sort_order}]

The functionality is available for [Admin, Manager, Reporter] roles.

### Retrieve System Events Collection [GET]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).
    
+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door
    
    + Body
    
            {
                "totalCount" : "1",
                "items": [
                    {
                        "id": "1",
                        "name": "MyEventRule",
                        "triggerType": "When allowed",
                        "action": "Delay Open",
                        "delay": "0:25:43",
                        "startTime": "12:00",
                        "stopTime": "23:00",
                        "recurring": [
                            "Monday",
                            "Tuesday"
                        ],
                        "singleDate": "2016-02-23",
                        "label": "",
                        "sourceDoors": [
                            {
                                "id": "1"
                            }
                        ],
                        "targetDoors": [
                            {
                                "id": "2"
                            }
                        ]
                    }
                ]
            }
            
+ Response 401 (application/json)
+ Response 500 (application/json)

## System Events [/system-events]

The functionality is available for [Admin] roles. Retrieving a System Event is also available for the [Manager, Reporter] roles.

### Retrieve a System Event [GET /system-events/{id}]

+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door
    
    + Body
    
            
            {
                "id": "1",
                "name": "MyEventRule",
                "triggerType": "When allowed",
                "action": "Delay Open",
                "delay": "0:25:43",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "label": "",
                "sourceDoors": [
                    {
                        "id": "1"
                    }
                ],
                "targetDoors": [
                    {
                        "id": "2"
                    }
                ]
            }
            
+ Response 401 (application/json)
+ Response 500 (application/json)

### Add a System Event Rule  [POST /system-events]

+ Request (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door

    + Headers
    
            Authorization: Bearer {token}

    + Body
    
            {
                "name": "MyEventRule",
                "triggerType": "When allowed",
                "action": "Delay Open",
                "delay": "0:25:43",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "sourceDoors": [
                    {
                        "id": "1"
                    }
                ],
                "targetDoors": [
                    {
                        "id": "2"
                    }
                ]
            }

+ Response 200 (application/json)

    + `id` (required, number) ... Id of created event rule.
    
    + Body
    
            {
                "id": "1"
            }
            
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Update a System Event Rule [PUT /system-events/{id}]

+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.

+ Request

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door

    + Headers
    
            Authorization: Bearer {token}
    + Body
    
            {
                "name": "MyEventRule",
                "triggerType": "When allowed",
                "action": "Delay Open",
                "delay": "0:25:43",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "sourceDoors": [
                    {
                        "id": "1"
                    }
                ],
                "targetDoors": [
                    {
                        "id": "2"
                    }
                ]
            }

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Delete a System Event Rule [DELETE /system-events/{id}]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.
    
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

# Group Auto Open
List of access rules that represent the times that doors should be propped open.

## Auto Open Rules Collection [/auto-open?page={page}&per-page={per_page}&sort={sort_order}]
The functionality is available for [Admin, Manager, Reporter] roles.
### Retrieve Auto Open Rules Collection [GET]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).
    
+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door
            
    + Body
    
            {
                "totalCount" : "1",
                "items": [
                    {
                        "id": "1",
                        "allow": "true",
                        "startTime": "12:00",
                        "stopTime": "23:00",
                        "recurring": [
                            "Monday",
                            "Tuesday"
                        ],
                        "singleDate": "2016-02-23",
                        "label": "",
                        "doors": [
                            {
                                "id": "1"
                            }
                        ]
                    }
                ]
            }
            
+ Response 401 (application/json)
+ Response 500 (application/json)

## Auto Open Rules [/auto-open]
The functionality is available for [Admin] roles. Retrieving a Auto Open Rule is also available for the [Manager, Reporter] roles.
### Retrieve an Auto Open Rule [GET /auto-open/{id}]

+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door
            
    + Body
    
            {
                "id": "1",
                "allow": "true",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "label": "",
                "doors": [
                    {
                        "id": "1"
                    }
                ]
            }

            
+ Response 401 (application/json)
+ Response 500 (application/json)

### Add an Auto Open Rule  [POST]

+ Request (application/json)

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    + Body
    
            {
                "allow": "true",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "doors": [
                    {
                        "id": "1"
                    }
                ]
            }

+ Response 200 (application/json)

    + `id` (required, number) ... Id of created rule.

    + Body
    
            {
                "id": "1"
            }
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Update an Auto Open Rule [PUT /auto-open/{id}]

+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.

+ Request

    +`recurring` (conditional required, array) List of days of a week when rule should be performed
    
    +`singleDate` (conditional required, string) Day when rule should be performed
    
    +`delay` (conditional required, string) Time to wait before open/close door

    + Headers
    
            Authorization: Bearer {token}
            
    + Body
    
            {
                "allow": "true",
                "startTime": "12:00",
                "stopTime": "23:00",
                "recurring": [
                    "Monday",
                    "Tuesday"
                ],
                "singleDate": "2016-02-23",
                "doors": [
                    {
                        "id": "1"
                    }
                ]
            }

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Delete an Auto Open Rule [DELETE /auto-open/{id}]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Rule to perform the action on.
    
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

# Group Floor Groups
Associates a reader input and a group of floor outputs. This group is then referenced from an elevator rule on a person or group to activate all the floor buttons in the elevator car where input reader is installed.
## Floor Groups Collection [/floor-groups?page={page}&per-page={per_page}&sort={sort_order}]
The functionality is available for [Admin] roles.
### Retrieve Floor Groups Collection [GET]
+ Parameters

    + page (optional, number, `0`) ... Number of page (by default 0).
    + per_page (optional, number, `10`) ... Count of items per page (by default 10).
    + sort_order (optional, string, `asc`) ... Sorting order. Can be "asc" or "desc" (by default asc).
    
+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    + Body
    
            {
                "totalCount" : "1",
                "items": [
                    {
                        "id": "1",
                        "label": " ",
                        "name": "FloorGroup1",
                        "readerPort": "1",
                        "floors": [
                            {
                                "id": "1"
                            }
                        ]
                    }
                ]
            }
            
+ Response 401 (application/json)
+ Response 500 (application/json)

## Floor Groups [/floor-groups]
The functionality is available for [Admin] roles.

### Retrieve a Floor Group [GET /floor-groups/{id}]
    
+ Request

    + Headers
    
            Authorization: Bearer {token}
    
+ Response 200 (application/json)

    + Body
    
            {
                "id": "1",
                "label": "",
                "name": "FloorGroup1",
                "readerPort": "1",
                "floors": [
                    {
                        "id": "1"
                    }
                ]
            }

            
+ Response 401 (application/json)
+ Response 500 (application/json)

### Add a Floor Group  [POST]

+ Request (application/json)

    + Body
    
            {
                "name": "FloorGroup1",
                "readerPortId": "1",
                "floors": [
                    {
                        "id": "1"
                    }
                ]
            }

+ Response 200 (application/json)

    + `id` (required, number) ... Id of created elevator.
    
    + Body
    
            {
                "id": "1"
            }
            
+ Response 400 (application/json)            
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Update a Floor Group [PUT /floor-groups/{id}]

+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Elevator to perform the action on.

+ Request

    + Headers
    
            Authorization: Bearer {token}
            
    + Body
    
            {
                "name": "Elevator1",
                "readerPort": "1",
                "floors": [
                    {
                        "id": "1"
                    }
                ]
            }

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)

### Delete a Floor Group [DELETE /floor-groups/{id}]
+ Parameters

    + id (required, string, `1`) ... Alphanumeric `id` of the Elevator to perform the action on.
    
+ Request

    + Headers
    
            Authorization: Bearer {token}

+ Response 204 (application/json)
+ Response 400 (application/json)
+ Response 401 (application/json)
+ Response 403 (application/json)
+ Response 404 (application/json)
+ Response 500 (application/json)